-- MySQL Script generated by MySQL Workbench
-- Sun Feb 9 13:31:35 2020 -- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mathLearningDB --
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mathLearningDB
-- -----------------------------------------------------
 CREATE SCHEMA IF NOT EXISTS `mathLearningDB` DEFAULT CHARACTER SET utf8 ;
 USE `mathLearningDB` ;

-- -----------------------------------------------------
-- Table `mathLearningDB`.`ACCOUNT`
-- -----------------------------------------------------
CREATE TABLE IF
NOT EXISTS `mathLearningDB`.`ACCOUNT` (
  `UserID` INT NOT NULL,
  `FName` VARCHAR(45) NULL,
  `LName` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phonenumber` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `PasswordHash` VARCHAR(45) NULL,
  `AccountType` VARCHAR(45) NULL,
  `CreatedTimestamp` FLOAT NULL,
  `ConsentBool` TINYINT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mathLearningDB`.`UNIVERSITY`
-- -----------------------------------------------------
CREATE TABLE IF
NOT EXISTS `mathLearningDB`.`UNIVERSITY` (
  `UID` INT NOT NULL,
  `UniversityName` VARCHAR(45) NULL,
  `TimeZone` VARCHAR(45) NULL,
  PRIMARY KEY (`UID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mathLearningDB`.`CLASS`
-- -----------------------------------------------------
CREATE TABLE IF
NOT EXISTS `mathLearningDB`.`CLASS` (
  `ClassID` INT NOT NULL,
  `ClassName` VARCHAR(45) NULL,
  `ClassCode` VARCHAR(45) NOT NULL,
  `StartTime` FLOAT NULL,
  `EndTime` FLOAT NULL,
  `UniversityID` INT NULL,
  PRIMARY KEY (`ClassID`, `ClassCode`),
  -- INDEX `UID_idx` (`UniversityID` ASC) VISIBLE,
  CONSTRAINT `CLASS_UID`
    FOREIGN KEY (`UniversityID`)
    REFERENCES `mathLearningDB`.`UNIVERSITY` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mathLearningDB`.`SURVEY_QUESTION`
-- -----------------------------------------------------
CREATE TABLE IF
NOT EXISTS `mathLearningDB`.`SURVEY_QUESTION` (
  `ClassID` INT NOT NULL,
  `SurveyQID` INT NOT NULL,
  `SurveyQuestion` VARCHAR(120) NULL,
  `Range` FLOAT NULL,
  PRIMARY KEY (`ClassID`, `SurveyQID`),
  -- INDEX `SurveyQID_idx` (`SurveyQID` ASC) VISIBLE,
  CONSTRAINT `SURVEYQ_CID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `mathLearningDB`.`CLASS` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mathLearningDB`.`CLASS_QUESTION`
-- -----------------------------------------------------
CREATE TABLE IF
NOT EXISTS `mathLearningDB`.`CLASS_QUESTION` (
  `ClassID` INT NOT NULL,
  `ClassQID` INT NOT NULL,
  `ClassQuestion` VARCHAR(120) NULL,
  `QuestionAnswer` VARCHAR(120) NULL,
  PRIMARY KEY (`ClassID`, `ClassQID`),
  CONSTRAINT `CLASSQ_CID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `mathLearningDB`.`CLASS` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mathLearningDB`.`SURVEY_RESPONSE`
-- -----------------------------------------------------
CREATE TABLE IF
NOT EXISTS `mathLearningDB`.`SURVEY_RESPONSE` (
  `RecordedDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ResponseId` INT NOT NULL,
  `RecipientLastName` VARCHAR(45) NOT NULL,
  `RecipientFirstName` VARCHAR(45) NOT NULL,
  `RecipientEmail` VARCHAR(255) NOT NULL,
  `Q1_1` INT NULL,
  `Q1_2` INT NULL,
  `Q1_3` INT NULL,
  `Q1_4` INT NULL,
  `Q1_5` INT NULL,
  `ClassID` INT NOT NULL,
  `StartTime` TIME NULL,
  `EndTime` TIME NULL,
  `ObsID` INT NULL,
  PRIMARY KEY (`ResponseId`, `RecordedDate`, `ClassID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mathLearningDB`.`CLASS_RESPONSE`
-- -----------------------------------------------------
CREATE  TABLE IF
NOT EXISTS `mathLearningDB`.`CLASS_RESPONSE` (
  `UserID` INT NOT NULL,
  `Timestamp` FLOAT NOT NULL,
  `ClassID` INT NOT NULL,
  `ClassQID` INT NOT NULL,
  `ClassAnswer` VARCHAR(120) NULL,
  PRIMARY KEY (`UserID`, `Timestamp`, `ClassQID`, `ClassID`),
  -- INDEX `CID_idx` (`ClassID` ASC) VISIBLE,
  -- INDEX `CQID_idx` (`ClassQID` ASC) VISIBLE,
  CONSTRAINT `CLASSR_CID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `mathLearningDB`.`CLASS` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
--  CONSTRAINT `CLASSR_CQID`
--   FOREIGN KEY (`ClassQID`)
--   REFERENCES `mathLearningDB`.`CLASS_QUESTION` (`ClassQID`)
--   ON DELETE NO ACTION
--   ON UPDATE NO ACTION,
  CONSTRAINT `CLASSR_UID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mathLearningDB`.`ACCOUNT` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mathLearningDB`.`IS_ENROLLED_IN`
-- -----------------------------------------------------
CREATE TABLE IF
NOT EXISTS `mathLearningDB`.`IS_ENROLLED_IN` (
  `StudentID` INT NOT NULL,
  `ClassID` INT NOT NULL,
  PRIMARY KEY (`StudentID`, `ClassID`),
  -- INDEX `CID_idx` (`ClassID` ASC) VISIBLE,
  CONSTRAINT `IEI_SID`
    FOREIGN KEY (`StudentID`)
    REFERENCES `mathLearningDB`.`ACCOUNT` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IEI_CID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `mathLearningDB`.`CLASS` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mathLearningDB`.`IS_ADMINISTERED_BY`
-- -----------------------------------------------------
CREATE TABLE IF
 NOT EXISTS `mathLearningDB`.`IS_ADMINISTERED_BY` (
  `ClassID` INT NOT NULL,
  `AdminID` INT NOT NULL,
  PRIMARY KEY (`ClassID`, `AdminID`),
  -- INDEX `AID_idx` (`AdminID` ASC) VISIBLE,
  CONSTRAINT `IAB_CID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `mathLearningDB`.`CLASS` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IAB_AID`
    FOREIGN KEY (`AdminID`)
    REFERENCES `mathLearningDB`.`ACCOUNT` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
